basePath: /
definitions:
  models.Installment:
    properties:
      created_at:
        type: string
      id:
        type: integer
      merchant_id:
        type: integer
      total_amount:
        type: number
      updated_at:
        type: string
      user_id:
        type: integer
    type: object
  models.InstallmentRecap:
    properties:
      created_at:
        type: string
      id:
        type: integer
      merchant_id:
        type: integer
      payments:
        items:
          $ref: '#/definitions/models.Payment'
        type: array
      remaining:
        type: number
      status:
        type: string
      total_amount:
        type: number
      updated_at:
        type: string
      user_id:
        type: integer
    type: object
  models.Merchant:
    properties:
      bank_account:
        type: string
      id:
        type: integer
      merchant_name:
        type: string
    type: object
  models.Payment:
    properties:
      amount:
        type: number
      created_at:
        type: string
      id:
        type: integer
      merchant_id:
        type: integer
      payment_method:
        type: string
      transaction_id:
        type: integer
      updated_at:
        type: string
      user_id:
        type: integer
    type: object
  models.User:
    properties:
      email:
        type: string
      id:
        type: integer
      name:
        type: string
    type: object
  utils.ErrorResponse:
    properties:
      details: {}
      error:
        type: string
      message:
        type: string
      status:
        type: integer
    type: object
host: localhost:8082
info:
  contact:
    email: m.iqmal.riffai@gmail.com
    name: API Support
  description: API untuk test MNC
  termsOfService: http://swagger.io/terms/
  title: MNC Test API
  version: "1.0"
paths:
  /installment:
    get:
      description: Menampilkan daftar semua cicilan
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Installment'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.ErrorResponse'
      summary: Get all installments
      tags:
      - installment
    post:
      consumes:
      - application/json
      description: Membuat cicilan baru
      parameters:
      - description: Data Cicilan
        in: body
        name: installment
        required: true
        schema:
          $ref: '#/definitions/models.Installment'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Installment'
        "400":
          description: Data tidak valid
          schema:
            $ref: '#/definitions/utils.ErrorResponse'
        "500":
          description: Kesalahan server
          schema:
            $ref: '#/definitions/utils.ErrorResponse'
      summary: Create new installment
      tags:
      - installment
  /merchants:
    get:
      description: Mengambil daftar semua merchant
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Merchant'
            type: array
        "500":
          description: Kesalahan server
          schema:
            $ref: '#/definitions/utils.ErrorResponse'
      summary: Get all merchants
      tags:
      - merchant
  /payments:
    get:
      description: Mengambil daftar semua pembayaran
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Payment'
            type: array
        "500":
          description: Kesalahan server
          schema:
            $ref: '#/definitions/utils.ErrorResponse'
      summary: Get all payments
      tags:
      - payment
    post:
      consumes:
      - application/json
      description: Membuat pembayaran baru
      parameters:
      - description: Data Pembayaran
        in: body
        name: payment
        required: true
        schema:
          $ref: '#/definitions/models.Payment'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Payment'
        "400":
          description: Data tidak valid
          schema:
            $ref: '#/definitions/utils.ErrorResponse'
        "500":
          description: Kesalahan server
          schema:
            $ref: '#/definitions/utils.ErrorResponse'
      summary: Create new payment
      tags:
      - payment
  /recap:
    get:
      description: Mengambil rekap cicilan dan status pembayaran
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.InstallmentRecap'
            type: array
        "500":
          description: Kesalahan server
          schema:
            $ref: '#/definitions/utils.ErrorResponse'
      summary: Get installment recap
      tags:
      - installment
  /users:
    get:
      description: Menampilkan daftar semua pengguna
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.User'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.ErrorResponse'
      summary: Get all users
      tags:
      - users
swagger: "2.0"
